cc_binary(
    name = "lib_tensorflow_model_run.so",
    linkshared = 1,
    srcs = ["my_tensorflow_model_run_lib.cc", "my_tensorflow_model_run_lib.h"],
    deps = [
        "//tensorflow/core:tensorflow",
    ]
)
