cc_binary(
    name = "lib_multi_contact_point_model.so",
    linkshared = 1,
    srcs = ["multi_contact_point_model_run_lib.cc", "multi_contact_point_model_run_lib.h"],
    deps = [
        "//tensorflow/core:tensorflow",
    ]
)
